### ISSUE TITLE
With CSS animation one frame can bleed into the previous frame

### ISSUE THREAD

**Issue by rob-smallshire** [nbedos/termtosvg#100]
I've run into a problem when using the new CSS animation mode where the top of the cursor from a following frame can bleed into the bottom of the current frame. We don't see the same with termtosvg version 0.8.0. Here are a couple of example screenshots:
<img width="752" alt="Screen Shot 2019-07-01 at 14 03 21" src="https://user-images.githubusercontent.com/1044137/60435856-e8bfca00-9c0a-11e9-8358-fb4ade250ac5.png">

<img width="752" alt="Screen Shot 2019-07-01 at 14 03 45" src="https://user-images.githubusercontent.com/1044137/60435875-f8d7a980-9c0a-11e9-9790-cde91d015a1f.png">

**Comment by nbedos** [comment]
Thank you for reporting this issue. Would you mind sharing an animation produced by termtosvg that exhibits this problem please?

Adding vertical spacing between frames will prevent the first line of a frame bleeding into the last line of the previous frame but it won't prevent line overlap inside a single frame. It seems that you're using a large font so maybe the problem has to do with hardcoded values for cell height and width in termtosvg.

**Comment by rob-smallshire** [comment]
Thank you for taking the time to look at this. Attached is a zip file containing the SVG file and a CSS file to go with it. We subsequently scale the SVG inside an HTML page – hence the large font you saw – but you see the same bleeding here in the original SVG.

[frame_bleed.zip](https://github.com/nbedos/termtosvg/files/3348759/frame_bleed.zip)

**Comment by nbedos** [comment]
Thanks, I just merged your PR.
