### ISSUE TITLE
Generate ligature glyphs.

### ISSUE THREAD

**Issue by amcgregor** [nbedos/termtosvg#102]
Howdy!  It's me again!  Alice!  ;^P

So, likely due to how the characters are individually placed on the SVG canvas, ligatures as supported by fonts such as Hasklig (or Hasklug, as is the case in my situation) are not utilized.  Ligature replacements would likely need to be baked into the SVG, e.g. storing the actual ligature glyph instead of the two distinct neighbouring ones, which would require some reading of font metric data.

For example, according to Hasklig's README, these are the ligature triggers: `<*` `<*>` `<+>` `<$>` `***` `<|` `|>`  `<|>` `!!` `||` `===` `==>` `<<<` `>>>` `<>` `+++` `<-` `->` `=>` `>>` `<<` `>>=` `=<<` `..` `...` `::` `-<` `>-` `-<<` `>>-` `++` `/=` `==`

> ![](https://github.com/i-tu/Hasklig/raw/master/hasklig_example.png)

It'd make it look so much nicer, though.  :)

Thanks!

**Comment by nbedos** [comment]
I realize it would be nice to have but it seems like too much work for a very niche use case. I don't see myself working on this anytime soon. Sorry.
