### ISSUE TITLE
termtosvg command not found

### ISSUE THREAD

**Issue by uptownhr** [nbedos/termtosvg#19]
I'm on Ubuntu 18.04 and just installed pip 2.7 and installed termtosvg with `pip install termtosvg`. 

However termtosvg is not in the correct path or my path is not set. What is it that I am not doing correctly here? I can see that ~/.local/lib/python2.7/site-packages/termtosvg exists.

**Comment by rmNULL** [comment]
This application requires Python >=3.5.

 `python3 -m pip --user termtosvg`

**Comment by uptownhr** [comment]
thank you, let me give that a shot.

**Comment by artivilla** [comment]
I can see it's installed when I look into:
```
❯ cd ~/.local/lib/python3.6/site-packages/
lxml/                       pyte-0.8.0.dist-info/       wcwidth/
lxml-4.2.4.dist-info/       termtosvg/                  wcwidth-0.1.7.dist-info/
pyte/                       termtosvg-0.5.0.dist-info/
```
My python v set is : ❯ pyenv version
3.6.5 (set by /usr/local/opt/pyenv/version)

and it's an installed pkg:

❯ pip3 list
Package        Version
-------------- ---------
beautifulsoup4 4.6.0
certifi        2018.4.16
chardet        3.0.4
idna           2.6
lxml           4.2.4
pip            18.0
pyte           0.8.0
rebound-cli    1.1.6a1
requests       2.18.4
setuptools     40.2.0
termtosvg      0.5.0
urllib3        1.22
urwid          2.0.1
wcwidth        0.1.7
wheel          0.31.1

But still getting the same command. Do I need to add something to my PATH?

**Comment by nbedos** [comment]
> Do I need to add something to my PATH?

Yes, most likely `~/.local/bin`. If it doesn't work, `pip3 show -f termtosvg` will show you where termtosvg has been installed.

**Comment by aeciolevy** [comment]
What should be the path to add, could anyone give an example?

This is what I got from pip3 show -f termtosvg
```
Location: /Users/aeciolevy/Library/Python/3.6/lib/python/site-packages
```

I added this to my path:

```
export PATH="/Users/aeciolevy/Library/Python/3.6/lib/python/site-packages/termtosvg:$PATH"
```

Now I am getting permission denied instead of command not found.

I am using macOS.

**Comment by nbedos** [comment]
@aeciolevy 
Could you show us the full output of `pip show -f termtosvg`? It should include a list of files, like so:

```
Name: termtosvg
Version: 0.6.0
Summary: Record terminal sessions as SVG animations
Home-page: https://github.com/nbedos/termtosvg
Author: Nicolas Bedos
Author-email: nicolas.bedos@gmail.com
License: BSD 3-clause license
Location: /home/nico/termtosvg/.venv/lib/python3.7/site-packages
Requires: pyte, lxml
Required-by: 
Files:
  ../../../bin/termtosvg
  termtosvg-0.6.0.dist-info/INSTALLER
  termtosvg-0.6.0.dist-info/LICENSE
  termtosvg-0.6.0.dist-info/METADATA
  termtosvg-0.6.0.dist-info/RECORD
  termtosvg-0.6.0.dist-info/WHEEL
  termtosvg-0.6.0.dist-info/top_level.txt
  termtosvg/__init__.py
  termtosvg/__pycache__/__init__.cpython-37.pyc
  termtosvg/__pycache__/anim.cpython-37.pyc
  termtosvg/__pycache__/asciicast.cpython-37.pyc
  termtosvg/__pycache__/config.cpython-37.pyc
  termtosvg/__pycache__/main.cpython-37.pyc
  termtosvg/__pycache__/term.cpython-37.pyc
  termtosvg/anim.py
  termtosvg/asciicast.py
  termtosvg/config.py
  termtosvg/data/templates/base16_default_dark.svg
  termtosvg/data/templates/dracula.svg
  termtosvg/data/templates/gjm8.svg
  termtosvg/data/templates/progress_bar.svg
  termtosvg/data/templates/solarized_dark.svg
  termtosvg/data/templates/solarized_light.svg
  termtosvg/data/templates/window_frame.svg
  termtosvg/data/templates/window_frame_js.svg
  termtosvg/main.py
  termtosvg/term.py
```

In my case the executable is located at `../../../bin/termtosvg`. This path is relative to the path given as "Location" so the path of the executable is in fact `/home/nico/termtosvg/.venv/bin/termtosvg` which means that the directory that should be added to `$PATH` is `/home/nico/termtosvg/.venv/bin/`.

**Comment by aeciolevy** [comment]
Hi Nicolas,

This is my output

```
Name: termtosvg
Version: 0.5.0
Summary: Record terminal sessions as SVG animations
Home-page: https://github.com/nbedos/termtosvg
Author: Nicolas Bedos
Author-email: nicolas.bedos@gmail.com
License: BSD 3-clause license
Location: /Users/aeciolevy/Library/Python/3.6/lib/python/site-packages
Requires: lxml, pyte
Required-by:
Files:
  ../../../bin/termtosvg
  termtosvg-0.5.0.dist-info/INSTALLER
  termtosvg-0.5.0.dist-info/METADATA
  termtosvg-0.5.0.dist-info/RECORD
  termtosvg-0.5.0.dist-info/WHEEL
  termtosvg-0.5.0.dist-info/top_level.txt
  termtosvg/__init__.py
  termtosvg/__pycache__/__init__.cpython-36.pyc
  termtosvg/__pycache__/anim.cpython-36.pyc
  termtosvg/__pycache__/asciicast.cpython-36.pyc
  termtosvg/__pycache__/config.cpython-36.pyc
  termtosvg/__pycache__/main.cpython-36.pyc
  termtosvg/__pycache__/term.cpython-36.pyc
  termtosvg/anim.py
  termtosvg/asciicast.py
  termtosvg/config.py
  termtosvg/data/templates/dracula.svg
  termtosvg/data/templates/gjm8.svg
  termtosvg/data/templates/progress_bar.svg
  termtosvg/data/templates/solarized_dark.svg
  termtosvg/data/templates/solarized_light.svg
  termtosvg/data/templates/window_frame.svg
  termtosvg/data/templates/window_frame_js.svg
  termtosvg/main.py
  termtosvg/term.py
```

In that case my path should be:
/Users/aeciolevy/Library/Python/bin/
Correct?

**Comment by janriemer** [comment]
I had the same issue on Kubuntu 18.04. When following @nbedos' instructions it has worked for me:
1. Check where termtosvg is installed with `pip show -f termtosvg`:
```
Name: termtosvg
Version: 0.6.0
Summary: Record terminal sessions as SVG animations
Home-page: https://github.com/nbedos/termtosvg
Author: Nicolas Bedos
Author-email: nicolas.bedos@gmail.com
License: BSD 3-clause license
Location: /home/jan/.local/lib/python3.6/site-packages
Requires: lxml, pyte
Files:
  ../../../bin/termtosvg
  termtosvg-0.6.0.dist-info/INSTALLER
  termtosvg-0.6.0.dist-info/LICENSE
  termtosvg-0.6.0.dist-info/METADATA
  termtosvg-0.6.0.dist-info/RECORD
  termtosvg-0.6.0.dist-info/WHEEL
  termtosvg-0.6.0.dist-info/top_level.txt
  termtosvg/__init__.py
  termtosvg/__pycache__/__init__.cpython-36.pyc
  termtosvg/__pycache__/anim.cpython-36.pyc
  termtosvg/__pycache__/asciicast.cpython-36.pyc
  termtosvg/__pycache__/config.cpython-36.pyc
  termtosvg/__pycache__/main.cpython-36.pyc
  termtosvg/__pycache__/term.cpython-36.pyc
  termtosvg/anim.py
  termtosvg/asciicast.py
  termtosvg/config.py
  termtosvg/data/templates/base16_default_dark.svg
  termtosvg/data/templates/dracula.svg
  termtosvg/data/templates/gjm8.svg
  termtosvg/data/templates/progress_bar.svg
  termtosvg/data/templates/solarized_dark.svg
  termtosvg/data/templates/solarized_light.svg
  termtosvg/data/templates/window_frame.svg
  termtosvg/data/templates/window_frame_js.svg
  termtosvg/main.py
  termtosvg/term.py
```
- `Location` is `/home/jan/.local/lib/python3.6/site-packages`
- `Files` is `../../../bin/termtosvg`
-> absolute path is `/home/jan/.local/bin/termtosvg`
2. Add the absolute path to your PATH:
```bash
$ export PATH="/home/jan/.local/bin:$PATH"
```
3. execute `termtosvg`

Thanks @nbedos for the instructions! :+1:

**Comment by nbedos** [comment]
@aeciolevy 
> In that case my path should be:
> /Users/aeciolevy/Library/Python/bin/
> Correct?

You should add this directory to the PATH variable, yes.

> I added this path and it did not work;
> /Users/aeciolevy/Library/Python/3.6/bin/

What message do you get when running the following shell command?
```$ /Users/aeciolevy/Library/Python/3.6/bin/termtosvg```

> Also, If I go directly to the folder and try to run ./termtosvg it starts and closes automatically the recording.

That's weird. Could you please run the following command in a shell and paste the result here?
```$ echo $SHELL```

**Comment by nbedos** [comment]
I'm closing this issue since it's been inactive for 9 days. If you're experiencing the same problem and the solutions described above do not help, leave a message here and I'll reopen the issue.

**Comment by xiaguoxin** [comment]
just add ~/.local/bin to PATH works for me.
