### ISSUE TITLE
terminal is reloaded while starting termtosvg 

### ISSUE THREAD

**Issue by SiteshSahoo** [nbedos/termtosvg#20]
Hi,

Whenever **termtosvg** is started the _.bashrc_ is reloaded. 
Can this be avoided ?

- Thanks

**Comment by nbedos** [comment]
On startup termtosvg creates a new shell and this shell loads all the usual configuration files. This way you have all your usual settings and aliases.

Why should loading ~/.bashrc be avoided?

**Comment by SiteshSahoo** [comment]
One simple reason to avoid this is, working in different environment/setup would need some specific settings and loading ~/.bashrc again will set those to default value... 
Ex : 
    Working in different projects in parallel. And in .bashrc, the **DEFAULT_WORKING_DIR = Project1**. When I switched to **Project2** and try to use termtosvg again I need to repeat all these Project2 specific settings. Which is an _overhead_.

**Comment by nbedos** [comment]
Seems quite specific, I don't think it should be the default behavior of termtosvg.

A solution would be to provide a `--command` option so that you could run:
```
termtosvg --command '/bin/bash --norc'
```
This would make termtosvg run '/bin/bash --norc' instead of $SHELL which would prevent bash from loading the configuration files. It could also be useful in other cases (recording a Python interpreter directly so that the call to python or ipython is not shown in the animation).

**Comment by SiteshSahoo** [comment]
The problem is more serious than it looks. I would never want to record  (even if execution is not a major issue) my pre configuration commands to svg file each time I use this utility. This will simply be irrelevant and not useful. So I feel this should be considered as a fault than enhancement.

Configurable option should be fine .. but again the question is about the default behavior (Whether to enable or disable this by default). Is there a real need to create a fresh shell always?

**Comment by nbedos** [comment]
Basically termtosvg sits between the shell that called it and the new shell it spawns so that it can capture all I/O of the 'new' shell. This is the only way I know of to capture all I/O of a shell.

**Comment by ylmrx** [comment]
Several things you probably wanna try : 

### no home

```sh
HOME=/tmp termtosvg
```
bash won't find the .bashrc and keep every you had in your previous environment (it'll fail to find your user-configs when launching programs so you'll have to specify them manually when lauching them)

### no bash

```sh
SHELL=sh termtosvg
```
it's another shell, it should be default... and still will carry your previous env.

> protip : don't do this with sh as it has quite a hard default behavior, install zsh maybe

### no weird bashrc

You definitely shouldn't have some project specific variables in a new bash session.
Maybe you wanna have these in a separate file, and run "`source [FILE]`" when in the new shell.

**Comment by nbedos** [comment]
The workaround for this is to call `termtosvg -c '/bin/bash --norc'` (or something similar) in order to prevent the shell from reading `~/.bashrc`.

See #83 and #84 for details about the `-c` option.
