### ISSUE TITLE
How about add a progress bar?

### ISSUE THREAD

**Issue by knktc** [nbedos/termtosvg#24]
Thank you for the awesome project！
How about add a progress bar to the recorded svg? It will show length of the animation.

[adb_show.svg.zip](https://github.com/nbedos/termtosvg/files/2162186/adb_show.svg.zip)

The attachment above is just a example, we manually add the progress bar to svg file.(sorry, I don't know how to attach svg file directly)

**Comment by vuuv** [comment]
In fact, we just add an animated `rect` element before `</svg>`.

here is the code snip:
```svg
  <rect width="0" height="2" fill="#ff5722">
    <animate attributeType="XML" attributeName="width" from="0" to="100%"
        dur="33333ms" begin="0ms;anim_last.end+0ms"/>
  </rect>
</svg>
```
just change attribute `dur` to a suitable time. 

I recommend adding 2 new options:
```
-p show progress bar.
-P progress bar code. `%(total_ms)s' for total time spent, in milliseconds.
```
`-P` is used for customize, default value could be:
```python
progress_bar = """
<rect width="0" height="2" fill="#ff5722">
    <animate attributeType="XML" attributeName="width" from="0" to="100%"
        dur="%(total_ms)s" begin="0ms;anim_last.end+0ms"/>
  </rect>"""
```
Thanks.

**Comment by nbedos** [comment]
Good idea! It requires reading an SVG file though, and that can't be done with the Python package I'm currently using for handling SVG (svgwrite). I'll probably have to replace it with lxml or something else first.

**Comment by vuuv** [comment]
my friend @knktc share this svg to me. I must to say its a great creative!
I think it should has a progress bar, that more cool, so I learned svg animation yesterday and hacked a new file through Chrome and `vim` command.

customize code is optional. and I hav'nt find a better plan yet. 
I just worry that my progress bar is so simple, and someone will wanna to prettify it.

**Comment by Earnestly** [comment]
I'm not too familiar with svg, however instead of providing `-P` as @vuuv described, why not generalise the idea and provide a kind of `--footer` option which takes an arbitrary svg file and merges it at the end?

On the other hand svg is already a standard format so it should be possible to write tools to modify the file without needing to implement more and more in termtosvg itself.  This would be far more ideal in my opinion.

**Comment by nbedos** [comment]
This use case will be covered by SVG templates. See #53 for further discussion.
