### ISSUE TITLE
Feature request: Pause button

### ISSUE THREAD

**Issue by PetterS** [nbedos/termtosvg#27]
For all recordings except really simple ones, I think a pause button will be useful. It will let users copy text etc. I expect that this would require embedded JS, though.

Combined with a progress bar for seeking etc., this feature would be even better.

**Comment by nbedos** [comment]
I agree, not being able to pause the animation is annoying. I'll look into it.

**Comment by vuuv** [comment]
@nbedos i'm interest to this too, this maybe help: http://edutechwiki.unige.ch/en/Interactive_SVG-SMIL_animation_tutorial#Stopping_.2F_pausing_animation

**Comment by ylmrx** [comment]
currently working on this.

**Comment by ylmrx** [comment]
https://github.com/ylmrx/termtosvg/blob/ylmrx-patch-1/playpause.svg
What do you think ? 
(right-click > display image). (see the red/green button upper right)
I need to implement the option to enable / disable it from CLI. 
I don't want to embed some image, or have an ugly text, the color code seems the best and most straightforward to me. If you or @nbedos has a better idea, advise.

**Comment by PetterS** [comment]
Nice! It works for me in Chrome and Firefox. But perhaps you can use Unicode ⏸ and ▶ for displaying the buttons?

**Comment by ylmrx** [comment]
ugly text meant "[PAUSE]" :) 
I guess all browsers which can SVG shouldn't fail to hard with these (basic) unicodes. It display like this now : https://github.com/ylmrx/termtosvg/blob/ylmrx-patch-1/termtosvg_k65gm89m.svg
I have to clean the code, and make a PR later this week ! Stay tuned :D

**Comment by ylmrx** [comment]
I wasn't able to make it before end of week, but here it is : 

# <3 

#45

**Comment by nbedos** [comment]
Here's the slider I'd like to add too.

You have to click on the red square to catch it and then you can slide it left or right to explore the whole timeline.

I know nothing about JS though so this part of the code will need some serious review.

[awesome.svg.zip](https://github.com/nbedos/termtosvg/files/2177936/awesome.svg.zip)

**Comment by styfle** [comment]
@nbedos I can review JS. I already took a look at #45 and left some comments.

**Comment by ylmrx** [comment]
I feel the slider needs quite some work (I don't know much about JS in such context). And will probably need deep modifications within `render_anim()` function. 
I feel it should be adressed in another issue ( #24  ). Still I love where this is going !

**Comment by nbedos** [comment]
This use case will be covered by SVG templates. See #53 for further discussion.
