### ISSUE TITLE
Losing my bash configuration 

### ISSUE THREAD

**Issue by rmNULL** [nbedos/termtosvg#29]
Hello,
 Whenever i run termtosvg, bash aliases and bashrc config are reset.
However, configs are restored at exit.
Is this the expected behaviour ?

 Trying this on _termux v0.63_ 

Cheers for the program and effort.

**Comment by nbedos** [comment]
Hi!
Nope, that's not expected. What's the output of `echo $SHELL` ? If you run bash inside bash, do you also lose aliases and settings from bashrc ?

**Comment by rmNULL** [comment]
No I don't lose my config if I nest bash. 

echoing $SHELL outputs blank string

**Comment by nbedos** [comment]
termtosvg runs the shell specified by the SHELL environment variable since it's the default shell for the current user. Try running `SHELL=/bin/bash termtosvg`, it should preserve the configuration of your shell. 

It's strange that in your case this variable is not set though.

**Comment by rmNULL** [comment]
Thanks, setting the shell variable seems to fix it.

Termux sets the SHELL variable to "/data/data/com.termux/files/usr/bin/login".
However it loads bashrc on regular usage. Anyway that's not the issue of this software. 

Thanks again.
