### ISSUE TITLE
Do not record with terminal size

### ISSUE THREAD

**Issue by pawamoy** [nbedos/termtosvg#30]
Am I right if I say that the terminal size is taken into account when recording? If so, would it be possible to change that so it is **not** taken into account? I was very glad that asciinema don't do this, and that you can resize it later with svg-term-cli. It would help with automation, as we would not need to resize the terminal before starting to record.

**Comment by nbedos** [comment]
I agree that resizing the terminal is annoying. There probably should be 'terminal lines' and 'terminal columns' properties in the configuration file, and also matching command line options.

I'll look into it.

**Comment by nbedos** [comment]
@pawamoy @styfle @kodie
This has been implemented, but it's not released yet. The code is available in the branch [feature/animation_UI](https://github.com/nbedos/termtosvg/tree/feature/animation_UI). I'll release this later when I'm done with other features that I'd like to include in the next release.

Basically you have to call `termtosvg --screen-geometry 80x19` or `termtosvg -g 80x19` to enforce a terminal size of 80 columns by 19 rows. The pending option in the configuration file is named 'screen-geometry'.

I haven't updated the README yet, but the command line usage is up to date:
```
$ termtosvg --help
usage: termtosvg [output_file] [--font FONT] [--theme THEME] [--screen-geometry GEOMETRY] [--verbose] [--help]
Record a terminal session and render an SVG animation on the fly

positional arguments:
  output_file           optional filename of the SVG animation; if missing, a
                        random filename will be automatically generated

optional arguments:
  -h, --help            show this help message and exit
  --font FONT           font to specify in the CSS portion of the SVG
                        animation (DejaVu Sans Mono, Monaco...). If the font
                        is not installed on the viewer's machine, the browser
                        will display a default monospaced font instead.
  --theme THEME         color theme used to render the terminal session (gjm8,
                        circus, classic-dark, classic-light, dracula, isotope,
                        marrakesh, material, monokai, solarized-dark,
                        solarized-light, zenburn)
  --verbose, -v         increase log messages verbosity
  --screen-geometry GEOMETRY, -g GEOMETRY
                        geometry of the terminal screen used for rendering the
                        animation. The geometry must be given as the number of
                        columns and the number of rows on the screen separated
                        by the character "x". For example "82x19" for an 82
                        columns by 19 rows screen
  --template TEMPLATE   SVG template used for the animation (plain, carbon,
                        progress_bar)

See also 'termtosvg record --help' and 'termtosvg render --help'
```

**Comment by pawamoy** [comment]
This is great @nbedos, I'm gonna try the branch in the next few days :slightly_smiling_face: Thanks!

**Comment by pawamoy** [comment]
Alright it seems good! I just ran a few tests and the rendered SVG looks great! I'll now be able to switch from asciinema+svg-term-cli to termtosvg only :smile:. Feel free to close when this branch is merged and released :slightly_smiling_face:

**Comment by nbedos** [comment]
@pawamoy 
Good to know! This feature is included in version 0.5.0 that has just been released.

**Comment by nbedos** [comment]
@masaeedu What error are you getting? Could you upload the asciicast so that I can take a look at it, please?

**Comment by masaeedu** [comment]
@nbedos I'm using the following set of commands:

```
termtosvg record ./test.cast
...type some stuff...
termtosvg render -g=100x30 ./test.cast ./output.svg
```

Here's the error message

```
usage: termtosvg render input_file [output_file] [-t TEMPLATE] [-v] [-h]
termtosvg: error: unrecognized arguments: -g=100x30
```

Here's the cast: https://gist.github.com/masaeedu/55967cbec59caf80bb1f713f4c2ba90c

**Comment by nbedos** [comment]
No, sorry the screen-geometry option is available only at recording time. It's used to resize the shell used for the recording. Resizing at rendering time is not possible.

**Comment by masaeedu** [comment]
@nbedos Ah, ok. In that case I guess you the issue can be closed.
