### ISSUE TITLE
How are animations themselves timed?

### ISSUE THREAD

**Issue by cookiengineer** [nbedos/termtosvg#32]
The title itself explains it.

I'm currently fiddling around with the SVG file in order to understand it better and to be able to manually save some space that I do not need (e.g. with detailed progress bars that can be accelerated).

Is there a way to tweak the "smoothness" of the details of e.g. a curl progress bar? I guess my SVG files get so big (> 2MB) because of those, as they seem to be in there with each sub-sub-percentage as a separate `<text>` element.

**Comment by nbedos** [comment]
The replay function takes a parameter named `min_frame_duration` which enforces a minimum duration for each frame. You could set it to say 0.100 seconds to reduce the number of frames and the size of the animation. This parameter can't be set on the command line though, you would have to modify the code. 

https://github.com/nbedos/termtosvg/blob/a1c502bfd3ed2f8cb053fefc62bee5c4c7a1f47a/termtosvg/term.py#L190

You might also want to check out the output of `termtosvg record`. It's the raw output of the recording with timing information (before it is aggregated by replay())

There is also a lot of duplicated information in the SVG animation itself. It does not help reduce the file size.

**Comment by cirocosta** [comment]
Hey @cookiengineer , as @nbedos  pointed out, maybe it's indeed better to not go for that in the final svg output, but instead, in the middle (the cast file).

Wanting to tweak my recordings, I created [asciinema-edit](https://github.com/cirocosta/asciinema-edit) - it takes a cast (which `termtosvg` produces) and then performs a transformation that you might want. 

For instance, in your case, you could open the cast with a terminal, remove the pieces you find either too repetitive and then later fix the timestamps with `asciinema-edit quantize`.

I hope it helps. 

thx!
