### ISSUE TITLE
SVG compression vs other file formats

### ISSUE THREAD

**Issue by ridhwaans** [nbedos/termtosvg#36]
I havent used it too much, but how does the svg compression compare to other formats like gif? Im talking about ~5s or 30s clips. Not really an issue, just want to start a discussion

**Comment by nbedos** [comment]
Here's an answer to a similar question I posted on [Hacker News](https://news.ycombinator.com/item?id=17449810).

> OP here. Sadly, SVG file size is not as small as I'd want it to be. The main problem is that a few attributes (x, y and lengthAdjust) have to be repeated on each text tag to position each character at the right place. I can't use CSS for this since those attributes are not styling attributes.
> 
> Using SVG definitions efficiently to avoid duplication is also not as easy as I thought it would be.
> 
> I have a few ideas on how to reduce file size, this is the next improvement I'm planning to work on.
> 
> For the examples shown at [1], file size ranges from 56kB to 252kB, the worst case scenario being lots of single characters with different colors.
