### ISSUE TITLE
Could not play the animation

### ISSUE THREAD

**Issue by franshesco** [nbedos/termtosvg#4]
Hi, 

 I am using ubuntu 18.04 with python3.6.5 and I have installed the requirement for termtosvg. Great tool when reading the description but I am not able to view the animation. When I try to view the animation, a windows appears with the name of the animation but nothing is displayed, just a frozen page.You can see the frozen page in the 
![screenshot from 2018-06-27 07-08-51](https://user-images.githubusercontent.com/10242040/41956188-a97906ac-79da-11e8-8a4a-8f573d5b06f9.png)
attached file

**Comment by nbedos** [comment]
Hi,

Did you try opening it with your web browser? Does it give the same result?
Can you upload the SVG animation so that I can take a look at it?

**Comment by franshesco** [comment]
Hello,

sorry I didn't think to try through the web browser and it works fine with. But I can't open the animation file via the command line. I used xdg-open, eog and some other commands that I have found but nothing is working. May be I am the one missing something. 

I have attached the file into a compressed folder.  
[termtosvg.tar.gz](https://github.com/nbedos/termtosvg/files/2145966/termtosvg.tar.gz)

**Comment by nbedos** [comment]
My mistake, I shouldn't have advised to open animated SVGs with an image viewer. I tested a few but it seems they do not have support for animated SVGs. On my machine, calling xdg-open with an SVG file opens a web browser so I did not see this problem.
I'll update the README to suggest opening SVGs with a web browser instead.

**Comment by franshesco** [comment]
ah okay, so work with the web browser only?

thx

**Comment by nbedos** [comment]
Yes. As far as I can tell it has nothing to do with termtosvg, it's just that those image viewers do not support SVG animations.

**Comment by franshesco** [comment]
okay, I understand. I can close my issue.

thx.
