### ISSUE TITLE
Import file in readme locally

### ISSUE THREAD

**Issue by jrock2004** [nbedos/termtosvg#41]
I have the following in my `README.md`

```
<div align="center">
  <img src="./readme/update-host-file.svg" />
</div>
```

If I load that file in the browser it works just fine. If I replace the source with the source you have in your readme I see it. I am wondering if maybe Github wants it to be linked to some external source?

**Comment by nbedos** [comment]
Yeah unfortunately you can't do that. See https://github.com/rgrove/rawgit/blob/master/FAQ.md for the reason.

You'll have to use something like https://rawgit.com/ to host your animation so that the SVG is served with the right content type.
