### ISSUE TITLE
function not found

### ISSUE THREAD

**Issue by drobati** [nbedos/termtosvg#46]
```
~ $ termtosvg 
Recording started, enter "exit" command or Control-D to end
bash: parse_git_branch: command not found
```

I've got a function that is executed in my prompt. 

```
# for prompt later
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

export PS1="\\[\\033[1;31m\\]\\W\\[\\033[1;33m\\]\$(parse_git_branch) \\[\\033[1;34m\\]λ\\[\\033[0m\\] "
```

Is there a way to define this in termtosvg

**Comment by nbedos** [comment]
Looks like bash does not load .bashrc. It could be the case if bash is called as `/bin/sh`. What's the output of `echo $SHELL`? Does running `SHELL=/bin/bash termtosvg` fix the problem?

termtosvg creates a new shell based on the content of the SHELL environment variable. If this variable is not defined then the shell is created by calling `/bin/sh`

See also #29

**Comment by drobati** [comment]
```
~ λ echo $SHELL
/bin/bash
~ λ termtosvg 
Recording started, enter "exit" command or Control-D to end
bash: parse_git_branch: command not found
~ λ echo $SHELL
/bin/bash
bash: parse_git_branch: command not found
```

**Comment by drobati** [comment]
I don't have a .bashrc. I'm on Mac, so I've just been using .bash_profile.

**Comment by drobati** [comment]
```
~ λ SHELL=/bin/bash termtosvg
Recording started, enter "exit" command or Control-D to end
bash: parse_git_branch: command not found
```
This didn't fix the problem, btw.

**Comment by drobati** [comment]
That bug you linked makes me think this is something to do with how I have bash configured.

```
~ λ bash
bash: parse_git_branch: command not found
~ λ echo $SHELL
/bin/bash
bash: parse_git_branch: command not found
~ λ exit
exit
~ λ echo "test"
test
```

As you can see opening a new bash shell, causes all my defined functions/alias to be 'forgotten'. I'm thinking this is because of the lack of a .bashrc.

**Comment by drobati** [comment]
Yeah that was the problem. I moved my config to a .bashrc and sourced it into my .bash_profile.

Works perfectly now.

**Comment by nbedos** [comment]
Yeah, `.bash_profile` is loaded by login shells, `.bashrc` is loaded by interactive, non login shells. termtosvg spawns an interactive non login shell so the configuration needs to be in `.bashrc`.

Thanks for the update!

**Comment by drobati** [comment]
Thanks for the awesome software!
