### ISSUE TITLE
Resulting images are causing 100% cpu on Chrome/Firefox

### ISSUE THREAD

**Issue by ahmetb** [nbedos/termtosvg#63]
I just recorded a ~100 kb svg animation with termtosvg.

Showing it in html bumps the Chrome or Firefox CPU usage straight to 100%. 

It seems like it's a browser issue but apparently it doesn't always happen either. 😕 Since I know nothing about SVG Animations and browsers I thought posting here might start a discussion –perhaps there's an improvement termtosvg can do (something like reducing draw rate/fps).

**Comment by nbedos** [comment]
Please upload the SVG so that I can take a look at it.

**Comment by ahmetb** [comment]
[krew_demo.txt](https://github.com/nbedos/termtosvg/files/2292691/krew_demo.txt)

please rename to .svg after downloading. GitHub doesn't allow svg uploads apparently.

**Comment by pkronstrom** [comment]
Same for me :) 100% CPU on Macos 10.13.1, Chrome version 68.0.3440.106 (Official Build) (64-bit)

[migrate-and-upgrade.txt](https://github.com/nbedos/termtosvg/files/2292793/migrate-and-upgrade.txt)

**Comment by Sliim** [comment]
Can't reproduce on debian/firefox, tested with uploaded animations

**Comment by markopolo123** [comment]
tested on macos 10.13.6 with firefox 62.0, can't reproduce with either file.

**Comment by nbedos** [comment]
Good to know, thanks for letting us know.
