### ISSUE TITLE
command not found: termtosvg

### ISSUE THREAD

**Issue by iostyle** [nbedos/termtosvg#65]
<img width="249" alt="image" src="https://user-images.githubusercontent.com/22219146/44200490-46753000-a179-11e8-96d3-52897173688e.png">

**Comment by iostyle** [comment]
MacOS 10.13.6

**Comment by iostyle** [comment]
Did I just use it wrong?

**Comment by nbedos** [comment]
It looks like the script used to run termtosvg was not installed or is not in your $PATH. Could you run the two following commands in your shell and copy/paste the output here? 

```
pip show -f termtosvg
echo $PATH
```

**Comment by iostyle** [comment]
<img width="1538" alt="image" src="https://user-images.githubusercontent.com/22219146/44244170-2e4af280-a205-11e8-8962-a9fea3ac4b79.png">

**Comment by iostyle** [comment]
I didn't find it in my bin

**Comment by iostyle** [comment]
Okay,I add location in PATH.

**Comment by nbedos** [comment]
What's the output of `pip show -f termtosvg` ?

**Comment by iostyle** [comment]
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/22219146/44309098-ed650080-a3f3-11e8-8cae-3ca6bca7be9d.png">

**Comment by nbedos** [comment]
Try adding /Users/iostyle/Library/Python/3.7/bin to PATH

**Comment by iostyle** [comment]
Thank you very much
