### ISSUE TITLE
Support box drawing escape sequences

### ISSUE THREAD

**Issue by astefanutti** [nbedos/termtosvg#7]
It'd be awesome to have support for:

https://en.wikipedia.org/wiki/Box-drawing_character#Unix,_CP/M,_BBS

So that we could export output such as:

https://github.com/chjj/blessed

**Comment by nbedos** [comment]
It works fine when using TERM=linux e.g.:
```$ TERM=linux termtosvg```

Sample recording: https://nbedos.github.io/termtosvg/random/issue_7/blessed.svg
