### ISSUE TITLE
Upgrade Mac OS to Python 3.7, but no command can be found after installation.

### ISSUE THREAD

**Issue by Cui-y** [nbedos/termtosvg#70]
As the title, I currently encounter the problem of not finding the command after installation, the installation process did not report an error, the screenshot is as follows：
￼
![image](https://user-images.githubusercontent.com/21211512/44317882-f7bfe280-a465-11e8-9cce-651e02f8f936.png)

**Comment by iostyle** [comment]
https://github.com/nbedos/termtosvg/issues/65

**Comment by Cui-y** [comment]
Thanks!
