### ISSUE TITLE
Record an entire `tmux` window

### ISSUE THREAD

**Issue by lenormf** [nbedos/termtosvg#72]
Hi,

From within a `tmux` window, `termtosvg` won't capture new panes that are created during recording. Is it feasible to have it record new panes as well?

Thanks.

**Comment by nbedos** [comment]
Yes, if you want to record all panes you have to run tmux inside termtosvg.

**Comment by lenormf** [comment]
The point is to record panes created after starting `termtosvg`, from within a `tmux` window.

Spawning an entire session after starting `termtosvg` is a workaround I can't really use, unfortunately.

**Comment by nbedos** [comment]
termtosvg records only the current shell, so when it's run inside a tmux pane it only has knowledge of this particular pane. I'm afraid the only way to record all panes of a window it to start a tmux session (or attach to an existing session) from within termtosvg.

**Comment by lenormf** [comment]
Alright, thanks.
