### ISSUE TITLE
Powerline fonts supporting

### ISSUE THREAD

**Issue by LeaForest** [nbedos/termtosvg#73]
It seems that termtosvg doesn't support powerline fonts.

When I use ` ZSH_THEME="agnoster"` in my .zshrc ,there is something wrong.

**Comment by nbedos** [comment]
Yeah, powerline fonts rely too much on the right character positioning for them to work with termtosvg. It might be possible to get it right but I spent some time on this problem and did not make any significant progress.
Something else to keep in mind: SVG animations produced by termtosvg do not contain fonts, unless you embed the font in the template yourself. So if you intend to publish the animation on the web you should probably stick to web safe fonts or are embed the font you're using in the template.

I'm closing this issue in favor of #14 where this subject was initially discussed. Please post any further comment over there.

**Comment by amcgregor** [comment]
> Yeah, powerline fonts rely too much on the right character positioning for them to work with termtosvg.

With just the quick note that there is absolutely no reason to believe these glyphs wouldn't work. Essentially, fixed width is fixed width and a glyph is a glyph. Here's using (and embedding) a font that includes them for Zsh and Vim, Hasklug, which took a few minutes with an online Data URI constructor, dragging in font weights to produce:

[![SVG with embedded font using Powerline symbols.](http://s.webcore.io/7a104d/2019-47-13--powerline.svg)](http://s.webcore.io/7a104d/2019-47-13--powerline.svg)

Worst in this are occasional de-syncs after a few loops, and that the arrow/chevron glyphs extend a pixel or two below the line proper.  See #14 ([this reply](https://github.com/nbedos/termtosvg/issues/14#issuecomment-500232350)) for the source template version.
