### ISSUE TITLE
On-the-fly modifications of colors while recording doesn't show, visually

### ISSUE THREAD

**Issue by trapd00r** [nbedos/termtosvg#79]
Breakdown of what I do and what I expect to happen:

- I change the value of color index 17 to 33 to 000. When I run my command outside of the new shell termtosvg creates, the visual feedback is instant. Inside, it's nothing. It doesn't matter if I run the c256 command prior to termsvg or after.
- That last command I use shows that, indeed, the color value of index 20 is changed to 000. Somehow termtosvg don't want to show it.

Which is kinda too bad, because I was very happy when I found termtosvg, and thought this would be perfect for some articles I am in the process of writing.

![fel](https://user-images.githubusercontent.com/43331/48969184-785d2480-effb-11e8-8d07-8bfdc7a13724.png)

**Comment by trapd00r** [comment]
When I use asciinema to record the above session, the playback shows exactly what's rendered at the terminal at the time of command execution.
If I use termtosvg to render that .cast file, the resulting svg doesn't show any colors change.

**Comment by nbedos** [comment]
I didn't even know that colors could be dynamically changed! The control sequence used to do this is an Xterm extension. termtosvg relies on [selectel/pyte](https://github.com/selectel/pyte) for rendering the screen of the terminal and Xterm extensions are out of the scope of their project. This is why the colors rendered by termtosvg are different than the ones shown by your terminal emulator.

I don't think this is something that can be fixed.

The authors of asciinema have written their very own terminal emulator which implements Xterm extensions so their terminal recorder does preserve the change in colors.

Out of curiosity, what's your use case for dynamically changing color values?
