### ISSUE TITLE
Advantages over asciinema + svg-term?

### ISSUE THREAD

**Issue by transitive-bullshit** [nbedos/termtosvg#8]
First off, this project looks really solid.  Just curious if there are any differences or advantages over using this program versus asciinema + [svg-term-cli](https://github.com/marionebl/svg-term-cli)?

I've used this approach in the past very successfully and have found that most people don't even know what "animated svg" really means. I also wrote about it [here](https://hackernoon.com/presenting-your-code-beautifully-fdbab9e6fb68).

Would love to hear your thoughts on the two approaches & thanks again for this project!

**Comment by nbedos** [comment]
I remember reading your article when pondering whether it was worth writing _another_ terminal recorder!
I tried svg-term-cli at some point but I thought the quality of some animations was sub-par. It might just be noticeable on my machine but when I look at [1]:
- the cursor partly covers the character on the left
- when the cursor reaches the bottom line of the screen, the line moves up and down by one pixel each time a character is entered.

Also, I don't know JavaScript and I'd rather have a tool written in Python that I can understand and easily fix. Better yet, a tool that can do the recording on its own!

[1] https://github.com/marionebl/svg-term-cli/blob/master/examples/chest.svg

**Comment by shelldandy** [comment]
Can you add terminal borders/padding like on the example you showed??

**Comment by transitive-bullshit** [comment]
Sounds good @nbedos -- thanks for the detailed reply!

I agree with @shelldandy that easily adding terminal UX would be a great feature to add :)

**Comment by gepandz** [comment]
The biggest advantage I see in this over asciinema is that this appears to be rendering locally, as opposed to sending things up to asciinema's servers. The latter gives my IT Security folks hives. This way, I get the benefits of terminal animations without risking my job. Win! ;-)

**Comment by shelldandy** [comment]
You can use asciinema without uploading to their servers with the --raw option then piping the result to svg-term-cli

https://github.com/asciinema/asciinema#rec-filename

**Comment by nbedos** [comment]
@transitive-bullshit @shelldandy I like the idea of adding terminal UX. How can this be made easily configurable? Provide a few sample SVG images in $HOME/.config/termtosvg/ux that be referenced to in the configuration file or on the command line? Users could also modify them or add their own (SVG) images in the folder and use them. 

Implementation probably won't be easy though. I'm currently using [svgwrite](https://github.com/mozman/svgwrite)  for writing SVG animations. I recently discovered it cannot be used to read SVG files, so I probably would have to switch to something else like lxml.

**Comment by transitive-bullshit** [comment]
Hmmm, [svg-term](https://github.com/marionebl/svg-term) seems to be rendering the UX via SSR react. Not sure how much that helps you, but in general I've been very happy with their output.

**Comment by marionebl** [comment]
Hey @nbedos, 

great work on `termtosvg`, I think it is amazing that there now is more than one solution for this! :heart: 

> I tried svg-term-cli at some point but I thought the quality of some animations was sub-par. It might > just be noticeable on my machine but when I look at [1]:

>    * the cursor partly covers the character on the left
>    * when the cursor reaches the bottom line of the screen, the line moves up and down by one pixel each time a character is entered.

I'll have a look at those issue sometime next week, comparing termtosvg to svg-term-cli output just might do the trick.

**Comment by marionebl** [comment]
> The biggest advantage I see in this over asciinema is that this appears to be rendering locally, as opposed to sending things up to asciinema's servers. The latter gives my IT Security folks hives. This way, I get the benefits of terminal animations without risking my job. Win! ;-)

@gepandz Apart from the plumbing commands @shelldandy suggested, `svg-term` also supports a `--cmd` flag, which opens an `asciinema` subshell and then process the resulting cast. That cast (or the contents of the asciinema subshell) never leave your machine, so no reason to make your ITSec people nervous 😄
