### ISSUE TITLE
Please consider moving the template manual to section 5

### ISSUE THREAD

**Issue by Earnestly** [nbedos/termtosvg#80]
As per the title, currently it's using section 1 which is typically for executables, whereas 5 is usually used for "File formats and conventions".

Currently I make this change locally by modifying the file to use `"5"` for the `.TH` title and install it as `.5` instead of `.1`.

**Comment by nbedos** [comment]
Thanks for the report. You're right, 5 is the right section. I've fixed this in 9b8cd11.

**Comment by Earnestly** [comment]
Thank you o/
