### ISSUE TITLE
Support --version

### ISSUE THREAD

**Issue by davidak** [nbedos/termtosvg#88]
`termtosvg: error: unrecognized arguments: --version`

tested using 0.6

**Comment by DannyBen** [comment]
Agree. I was also surprised there was no `--version`.

**Comment by nbedos** [comment]
Yeah, I forgot about that but it's a valid issue. For Python applications I usually use either `pip` or the package manager of my OS to get the version of a package. A `--version` CLI flag always seemed redundant to me and so I never included it.

**Comment by DannyBen** [comment]
> A --version CLI flag always seemed redundant to me and so I never included it.

I can understand that, but don't forget that:

1. For you, it is a python application, for other users, its just a CLI tool that happens to be installed with pip.
2. Other than `-h, --help`, it is probably the most widely used flag in CLI tools.
3. It is also sort of the go-to command to run to test if the app is installed. Its a second nature to install something than `--version` it :)
