### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by tsiq-swyx** [nbedos/termtosvg#9]
hey! congrats on launching in HN!

the install went fine but i get this when i run it:

```
 ✝  ~/OpenSource/OpenSourceApps   master  termtosvg
Traceback (most recent call last):
  File "/usr/local/bin/termtosvg", line 7, in <module>
    from termtosvg.__main__ import main
  File "/Library/Python/2.7/site-packages/termtosvg/__main__.py", line 144
    print(record.to_json_line(), file=cast_file)
                                     ^
SyntaxError: invalid syntax
```

is python 2.7 not supported?

**Comment by jwilk** [comment]
README says:
> termtosvg is compatible with Python >= 3.5

That said, the way the program fails is not very helpful.

**Comment by tsiq-swyx** [comment]
lol. cant believe i missed that. i'm gonna close, feel free to reopen if 2.7 support is easy
