### ISSUE TITLE
"No matching distribution found for fcntl"?

### ISSUE THREAD

**Issue by colemanlee** [nbedos/termtosvg#90]
OS version:Microsoft Windows 10 version 1803
Python version:Python 3.7.2

> $ python3 termtosvg
> Traceback (most recent call last):
>   File "termtosvg", line 3, in <module>
>     import termtosvg.main
>   File "D:\Program Files (x86)\Python\Python37-32\lib\site-packages\termtosvg\main.py", line 11, in <module>
>     import termtosvg.anim
>   File "D:\Program Files (x86)\Python\Python37-32\lib\site-packages\termtosvg\anim.py", line 13, in <module>
>     from termtosvg import term
>   File "D:\Program Files (x86)\Python\Python37-32\lib\site-packages\termtosvg\term.py", line 16, in <module>
>     import fcntl
> ModuleNotFoundError: No module named 'fcntl'

---

> $ python3 -m pip install fcntl
> Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
> Collecting fcntl
>   Could not find a version that satisfies the requirement fcntl (from versions: )
> No matching distribution found for fcntl

**Comment by nbedos** [comment]
There is no support for Windows, sorry. See https://github.com/nbedos/termtosvg/issues/13
