### ISSUE TITLE
Animation loop issue: frame not displayed

### ISSUE THREAD

**Issue by nmattia** [nbedos/termtosvg#94]
It sometimes happens that every other loop fails to render part of the SVG. [Here](https://camo.githubusercontent.com/6d0debdd99f6334ea82e0b5d1a87513da3da5df1/68747470733a2f2f6e69762e6e6d61747469612e636f6d2f6e69762e737667)'s an example: every now and then when the page loads the SVG, the animation is broken, and the first part of the text is shown only every other time.

**Comment by nbedos** [comment]
I couldn't reproduce it at first but if I open the animation in multiple tabs with Chromium it's indeed broken. It seems like one animation is interfering with the other. I'll look into this. 

Thanks for the report!

**Comment by nbedos** [comment]
This should be fixed by c9a3ecb. The behavior you noticed seems specific to SMIL animations: I've changed termtosvg to use either CSS animations or the Web Animations API and I can't reproduce this issue anymore.

**Comment by nmattia** [comment]
Works like a charm! thanks for looking into this. (added benefit: i can now source my SVGs directly from the repo on GitHub 🎉 )
