### ISSUE TITLE
Don't truncate last period of inactivity?

### ISSUE THREAD

**Issue by pawamoy** [nbedos/termtosvg#95]
I have demo scripts that I run through [pawamoy/shelldemo](https://github.com/pawamoy/shelldemo), so my recordings with termtosvg are automated.

It means that at the end, I don't type exit or Ctrl-D, and therefore nothing else is written in the terminal.

But I like to add a pause (sleep N) to give time to the reader to read the last command's output. It seems termtosvg truncates this because there is no more activity at the end.

Is this a thing that could be "fixed" (I don't think it should be considered a bug) or termtosvg absolutely needs a last write to keep that period of inactivity?

**Comment by nbedos** [comment]
Yes, the last period of inactivity is truncated and the last frame is displayed for 1 second. In c9a3ecb I've added a `-D` switch to the command line interface to specify the delay between two loops of the animation.

For example `termtosvg -D 1234` will display the last frame for 1234 milliseconds. See https://github.com/nbedos/termtosvg/blob/develop/man/termtosvg.md#-d---loop-delaydelay

**Comment by nbedos** [comment]
This is included in version [0.9.0](https://github.com/nbedos/termtosvg/releases/tag/0.9.0)
