### ISSUE TITLE
Emojis mess up layout

### ISSUE THREAD

**Issue by felixfbecker** [nbedos/termtosvg#96]
iTerm2:

![image](https://user-images.githubusercontent.com/10532611/58753152-86649400-84bb-11e9-9451-faee80767685.png)

term2svg:

![image](https://user-images.githubusercontent.com/10532611/58753159-a300cc00-84bb-11e9-99a2-6a02b0541762.png)

[out.log](https://github.com/nbedos/termtosvg/files/3244190/out.log)

**Comment by felixfbecker** [comment]
Also, `ESC[2m` (dimmed) has no effect.

**Comment by nbedos** [comment]
Good find, I didn't take into account that some Unicode characters take the space of 2 or more 'regular' characters. This should be fixed by 391d998.

> Also, `ESC[2m` (dimmed) has no effect.

Unfortunately this is not handled by [Pyte](https://github.com/selectel/pyte/) (which termtosvg uses to decode escape sequences).

**Comment by nbedos** [comment]
Fixed in https://github.com/nbedos/termtosvg/releases/tag/0.9.0
