### ISSUE TITLE
build standalone binary

### ISSUE THREAD

**Issue by setop** [nbedos/termtosvg#99]
I used [Pysintaller](http://www.pyinstaller.org/) with the following command : `use pyinstaller --clean --ascii --strip --onefile --name termtosvg --hidden-import pyte --hidden-import lxml --add-data termtosvg/data/templates:termtosvg/data/templates __main__.py`

Maybe it could be added to the documentation, if helpful.

**Comment by nbedos** [comment]
Thanks but I'd rather not get involved with packaging. Adding this as a note to the documentation means I both have to test it and provide support for it, which I'm not willing to do. I'd rather leave packaging to package maintainers.
